# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y

# Change idle settings
# 1.800.000 ms = 30 min
CONFIG_ZMK_IDLE_TIMEOUT=1800000 

# Deep sleep settings
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Custom keyboard name (max. 16 characters)
CONFIG_ZMK_KEYBOARD_NAME="fukuro"
